/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface BalanceDTO {
  Data: {
    Address: string;
    Network: string;
    TokenName: string;
  };
  RequestID: string;
  ServerDateTime: Date;
  UserID: string;
}

export interface CreateWalletDTO {
  Data: {
    Network: string;
    TokenName: string;
  };
  RequestID: string;
  ServerDateTime: Date;
  UserID: string;
}
